apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flow
  template:
    metadata:
      labels:
        app: flow
    spec:
      containers:
        - name: flow
          image: travy504/flow-based-programming:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
          - name: RABBITMQ
            value: "amqp://136.62.252.13:41003"
